### ISSUE TITLE
[GeoMechanicsApplication] Investigate the setup of GeoMechanicsApplication github documentation

### ISSUE THREAD

**Issue by indigocoral** [KratosMultiphysics/Kratos#11951]
To be consistent with Kratos Multiphysics documentation and to have all the documentation in public and up to date with our recent changes, we will be putting our documents in here:
[https://kratosmultiphysics.github.io/Kratos/](https://kratosmultiphysics.github.io/Kratos/ )

This issue aims to investigate how to add our application and start up our documentation page keeping in mind our team consensus that we would like to keep our documentation close to the source code.

**Comment by rfaasse** [comment]
@mcgicjn2 After an investigation and discussions with @indigocoral and @avdg81, this is the status of this issue. I noted some background info on the process and focused on our main problem we want to tackle: Keeping documentation close to the source, but still use them in github.io. In summary: there is no clear and simple answer. I would like to discuss in the team how we proceed with this (e.g. deeper investigations, discussions with CIMNE, some other option) and also what our purpose is for this documentation (e.g. is it mainly/only for users or also for devs).

## Background on Github IO process
In short, the github.io pages are built from the `docs` folder in the repository, and being compiled into a website. The `docs` folder can contain any type of file, but markdown files are the most common. The markdown files are built into an html site using jekyll. 

I created the following script to describe the steps needed to build the github.io pages locally.
```
#!/bin/bash

cd docs
python3 process_pages.py -t local
cd scripts
./build_site.sh
cd ../_site/Page_files
jekyll serve`
```
Running this script builds the pages and opens a local server to view the pages.

**_Note: I could only succesfully complete this workflow on a linux system (using WSL), not directly on windows._**

Adding a Geomechanics Application entry is as simple as adding a folder in `docs` and adding a markdown file in that folder, or create subfolders for more structure.

## Different linking possibilities

One of our own requirements as a team is that the documentation is easily reachable from the source code it describes. There are a few ways this can be achieved, which will be described in the following sections. In short, the investigated options are:
1. [Symbolic links](#symbolic-links)
2. [Relative links](#relative-links)

### Symbolic links

It is possible to keep the documentation close to the source code and create symbolic links to the documentation in the `docs` folder. This is the most straightforward way to link the documentation to the source code. When testing the doc page locally, this worked correctly (the file in the docs folder was only a symbolic link to the actual one in the source code:

![Image](https://github.com/KratosMultiphysics/Kratos/assets/56549273/0fbc6516-354d-47ab-a051-7a4863705d91)

However, it has a significant number of drawbacks:
1. Creating symlinks is a linux option, and not available on Windows (or only in administrative mode). This means that the documentation in the docs folder will not be easily reachable on Windows. If it is ever required that the github.io pages are built on Windows, this might be a problem.
2. Symlinks are not updated when the source file is (re)moved. This means that the documentation will be broken in that case and will require manual fixing.
3. Although it should be possible to push symlinks to github, it does not seem to straight-forward and might require some extra configuration steps for a developer who wants to 
4. Any referred images or other resources in the documentation, also need a symbolic link. Not a huge problem, but it is easily forgotten and can only be found when opening the specific page in the browser.

### Relative links

Markdown allows for using relative links to be able to navigate quickly to different markdowns. This can be used in two ways:
1. In the markdown file in the docs folder, try to link to the source code markdown file. However, the generated github.io page will not be able to find the source code markdown file, as it is not in the same folder.
2. In the source code markdown file, link to the documentation markdown file. This will work when navigating in e.g. IDES, however, the 'real' documentation is not close to the source code, only a link to it. Therefore, this is also not an ideal option.

### Extract the documentation from the source code when building the github.io page

This option has not really been explored, but it might be possible to add functionality to the build scripts to copy the documentation from the source code to the github.io pages. However, this would require us to maintain this new way of docs generation and needs to be discussed with CIMNE. I'm inclined to say this is too much work and error-prone for the benefit it brings.

**Comment by mcgicjn2** [comment]
Looks good

**Comment by indigocoral** [comment]
After discussion with the team, it was decided to contact Suneth and Charlie as the next step and see if they have a solution to keeping documentation close to the source, while also generating them in github.io.

**Comment by rfaasse** [comment]
### Proposal for GeoMechanics documentation generation for github pages

As the geomechanics team, we are putting significant effort into creating comprehensive documentation for our code and tests. Although this documentation is already available publicly in the repository, we would like to start using github pages to make it more accessible to the community and be consistent with Kratos Core and the other applications in Kratos.

As a team, we feel that the documentation should be placed close to the source code and tests, such that it is easy to maintain, use and and update from a development perspective. However, the generation of github pages uses the docs folder in the repository. We would like to propose the following steps to generate the documentation for the GeoMechanics application on github pages, while retaining the advantages of having the documentation close to the source code.

The following build steps are used in the workflow to generate the documentation for the KratosMultiphysics project on github pages (see the [yml script](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/workflows/jekyll-gh-pages.yml)). I have added a comment to the script to indicate where we would like to add a step to copy the documentation files which are stored close to the GeoMechanics source code and tests to the main/docs folder. Preferably, this is a  bash script that is maintained by the GeoMechanics team, such that we have control over how the documentation is structured. This could be easily extended to other applications who would like to take the same approach. It could also be standardized by creating the bash script with a standard name and each application which needs to do specific steps for the documentation generation can define them in that script.
```yaml
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout static page content
        uses: actions/checkout@v4
        with:
          repository: KratosMultiphysics/Documentation
          ref: master
          path: statik_content
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          path: main
      - name: Configure page content
        shell: bash
        run: cp -r statik_content/Page_files/* main/docs/
        # After the 'Configure Page content' step
        # we would like to add a step to copy the documentation 
        # files which are stored close to the GeoMechanics source 
        # code and tests to the main/docs folder. 
        
        # Proposed step -----------------------------------
      - name: Gather documentation files from Geomechanics
        shell: bash
        run: <path to bash script in geomechanics>/generate_docs.sh   
        # End of proposed step -----------------------------
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Create navigation menus
        shell: bash
        run: cd main/docs && python3 process_pages.py -t web
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./main/docs
          destination: ./main/docs/_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./main/docs/_site
```
